import json
import boto3

client = boto3.client("bedrock-agent-runtime")


# Function that extracts the relevant details about companies given their IDs
def extract_details(company_ids, queries, fields):
    details = {}

    # Loop over the companies and extract each fields
    for company_id in company_ids:
        response = {}
        for field, query in zip(fields, queries):
            query_response = client.retrieve_and_generate(
                input={
                    "text": f"{query}. The response must be as short as possible (one word in most cases). If you dont know answer with just NA."
                },
                retrieveAndGenerateConfiguration={
                    "knowledgeBaseConfiguration": {
                        "knowledgeBaseId": "Q90NJWWUIA",
                        "modelArn": "anthropic.claude-3-5-sonnet-20241022-v2:0",
                        "retrievalConfiguration": {
                            "vectorSearchConfiguration": {
                                "filter": {
                                    "equals": {
                                        "key": "Company_ID",
                                        "value": company_id,
                                    },
                                }
                            }
                        },
                    },
                    "type": "KNOWLEDGE_BASE",
                },
            )

            response[field] = query_response["output"]["text"]
        details[company_id] = response
    return details


def lambda_handler(event, context):

    # Fields to extract given in the form of query
    queries = [
        "Extract Company Name. The official name of the company or organization. The name of the company that is presenting the report. It can also be called as Business Name, Organization Name, Corporation name. The output must be in this format: Text. An example for the format: Apple Inc.",
        "Extract Symbol. The stock ticker symbol assigned to the company, used for trading on stock exchanges. It can also be called as Ticker symbol, Stock Symbol, Company ticker. The output must be in this format: Text. An example for the format: AAPL",
        "Extract Growth Rate. The annual growth rate (as a percentage). The percentage increase over a period of time. It can also be called as (CAGR), Revenue Growth, Earnings Growth. The output must be in this format: Int - Percentage. An example for the format: 15.20%",
        "Extract Revenue. The total income generated by the company from its normal business activities. The summation of all current and non current assets and liabilities of the company . It can also be called as Sales, Turnover, Top Line. The output must be in this format: Int. An example for the format: $100 Billion or ₹2,000 crore",
        "Extract Net Profit Margin. A financial ratio representing net profit as a percentage of revenue, indicating profitability. The percentage of revenue that remains as profit after all expenses have been deducted. It can also be called as Profit Margin, Net Margin, Bottom Line. The output must be in this format: Int - Percentage. An example for the format: 15.20%",
        "Extract ROE. A measure of financial performance calculated as net income divided by shareholders' equity. It can also be called as Return on Shareholders' Equity. The output must be in this format: Int - Percentage. An example for the format: 15.20%",
        "Extract ROA. A financial ratio indicating how profitable a company is relative to its total assets. It can also be called as Return on Total Assets. The output must be in this format: Int - Percentage. An example for the format: 15.20%",
        "Extract Market Cap. The total market value of a company's outstanding shares of stock. Calculated as share price multiplied by the number of outstanding shares. It can also be called as Market capitalisation, Market Value, Company Value. The output must be in this format: Int. An example for the format: $2 Trillion",
        "Extract Price to Earnings Ratio. The ratio of a company's stock price to its earnings per share. It can also be called as P/E, Price Multiple, Earnings Multiple. The output must be in this format: Int. An example for the format: 25",
        "Extract EPS. The portion of a company's profit allocated to each outstanding share of common stock. It can also be called as Earnings per Share. The output must be in this format: Int - Currency. An example for the format: $5.00",
        "Extract GHG Emissions. The total amount of greenhouse gases released into the atmosphere by a company's operations. It can also be called as Carbon Footprint of the company, Greenhouse Gas Footprint, Emissions. The output must be in this format: Text. An example for the format: Metric tons of CO2 equivalent (e.g.,'100,000 metric tons CO2e')",
    ]
    company_ids = json.loads(event["body"])["company_ids"]
    fields = [
        "Company Name",
        "Symbol",
        "Growth Rate",
        "Revenue",
        "Net Profit Margin",
        "ROE",
        "ROA",
        "Market Cap",
        "Price to Earnings Ratio",
        "EPS",
        "GHG Emissions",
    ]

    responses = extract_details(company_ids, queries, fields)
    return responses
